spring.application.name=backend

# Server
server.port=8080
server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/backendDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


google.web.client.id=${GOOGLE_WEB_CLIENT_ID}
nextauth.secret=${NEXTAUTH_SECRET}

//mail gun
mailgun.api.key=${MAILGUNAPI}

mailgun.domain=${MAILGUNDOMAIN}
adfda

google.client.id=YOUR_GOOGLE_CLIENT_ID
google_web_client_id=GOOGLE_WEB_CLIENT_ID
google_ios_client_id=GOOGLE_IOS_CLIENT_ID
google.client.secret=YOUR_GOOGLE_CLIENT_SECRET
google.redirect.uri=http://localhost:8080/auth/google/callback
frontend.redirect.url=http://localhost:3000
app.cookie.secure=false
jwt.secret=akjflkadjflkadjflkadjflkadjflkajdslfajslk
apple.client.id=APPLE_CLIENT_ID
apple.team.id=APPLE_TEAM_ID
apple.key.id=APPLE_KEY_ID
apple.redirect.uri=https://app-javabackend-5e1ae1d5056c.herokuapp.com/auth/apple/callback
apple.private.key=APPLE_PRIVATE_KEY