package com.backend.backend.enums;

public enum PinAuditEventType {
    PIN_CREATED,
    PIN_GENERATED,
    PIN_REPLACED,
    PIN_REVOKED,
    PIN_LOGIN_SUCCEEDED,
    PIN_LOGIN_FAILED,
    PIN_LOCKED,
    PIN_UNLOCKED_BY_MANAGER,
    PIN_OFFLINE_SUCCESS,
    PIN_OFFLINE_FAILURE,
    PIN_OFFLINE_LOCKED,
    PIN_BUNDLE_REFRESHED,
    PIN_VERIFIER_STALE,
    IPAD_DEVICE_ENROLLED,
    IPAD_DEVICE_REVOKED
}
